"""remake refrigerator_table

Revision ID: 072609986d95
Revises: 6ae36185bf5c
Create Date: 2026-05-04 16:54:19.804240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072609986d95'
down_revision = '6ae36185bf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refrigerator',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refrigerator')
    # ### end Alembic commands ###
