"""add memo to dish

Revision ID: 6354f1e70e3e
Revises: dea607a307b5
Create Date: 2026-04-29 15:59:16.665008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6354f1e70e3e'
down_revision = 'dea607a307b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
