"""initial

Revision ID: 6ae36185bf5c
Revises: 
Create Date: 2026-05-03 23:15:02.212062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae36185bf5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
