"""initial

Revision ID: 818ce5d67f0f
Revises: 
Create Date: 2026-05-15 18:20:42.034956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818ce5d67f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('dish',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('dish_id'),
    sa.UniqueConstraint('dish_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingredient',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.Column('ing_name', sa.String(length=20), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.cat_id'], ),
    sa.PrimaryKeyConstraint('ing_id'),
    sa.UniqueConstraint('ing_name')
    )
    op.create_table('ing_dish_set',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'ing_id')
    )
    op.create_table('refrigerator',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ing_id')
    )
    op.create_table('shopping_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    op.drop_table('refrigerator')
    op.drop_table('ing_dish_set')
    op.drop_table('ingredient')
    op.drop_table('user')
    op.drop_table('dish')
    op.drop_table('category')
    # ### end Alembic commands ###
