"""add shopping_list table

Revision ID: 99a23e58ce33
Revises: 6354f1e70e3e
Create Date: 2026-04-29 19:46:22.810662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a23e58ce33'
down_revision = '6354f1e70e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
