"""init

Revision ID: aa8745ce8aa8
Revises: 
Create Date: 2026-04-27 22:18:24.302726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8745ce8aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('dish',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('dish_id'),
    sa.UniqueConstraint('dish_name')
    )
    op.create_table('ingredient',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.Column('ing_name', sa.String(length=20), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.cat_id'], ),
    sa.PrimaryKeyConstraint('ing_id'),
    sa.UniqueConstraint('ing_name')
    )
    op.create_table('ing_dish_set',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'ing_id')
    )
    op.create_table('refrigerator',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refrigerator')
    op.drop_table('ing_dish_set')
    op.drop_table('ingredient')
    op.drop_table('dish')
    op.drop_table('category')
    # ### end Alembic commands ###
