"""add refrigerator table

Revision ID: c83ad6dee498
Revises: 8cc0078391cb
Create Date: 2026-04-24 21:02:13.789941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83ad6dee498'
down_revision = '8cc0078391cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refrigerator',
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.PrimaryKeyConstraint('ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refrigerator')
    # ### end Alembic commands ###
