"""add added_at

Revision ID: dea607a307b5
Revises: aa8745ce8aa8
Create Date: 2026-04-28 19:48:38.763633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea607a307b5'
down_revision = 'aa8745ce8aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refrigerator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refrigerator', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
