"""remake shopping_list

Revision ID: e1c483b52baa
Revises: 072609986d95
Create Date: 2026-05-04 17:36:50.803357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c483b52baa'
down_revision = '072609986d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ing_id'], ['ingredient.ing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
